#!/usr/bin/env bash
# shellcheck disable=SC2044,SC2155,SC2317
ywt:info() {
    package() {
        [[ -n "$YWT_PACKAGE" ]] && echo "$YWT_PACKAGE" && return 0
        local YWT_PACKAGE && YWT_PACKAGE=$(jq -c <"./package.json" 2>/dev/null) && export YWT_PACKAGE && readonly YWT_PACKAGE
        echo "$YWT_PACKAGE"
    }
    welcome() {
        local YWT_PACKAGE=$(package)
        local NAME && NAME=$(jq -r '.name' <<<"$YWT_PACKAGE") && readonly NAME
        local VERSION && VERSION=$(jq -r '.version' <<<"$YWT_PACKAGE") && readonly VERSION
        local DESCRITPTION=$(jq -r '.description' <<<"$YWT_PACKAGE")
        local URI && URI=$(jq -r '.homepage' <<<"$YWT_PACKAGE") && readonly URI
        colors hyperlink "$URI" "$(colors apply "yellow" "${NAME}@${VERSION} | ${DESCRITPTION} | $URI")" | logger info       
        # "Yellow Team"
        # ?utm_source=yellowteam&utm_medium=cli&utm_campaign=yellowteam
    }
    copyright() {
        echo "# YELLOW TEAM BUNDLE"
        echo "# $(jq -c .yellowteam <<<"$YWT_CONFIG")"
        echo "# This file is generated by yellowteam sdk builder. Do not edit this file"
        echo "# Build date: $(date -Iseconds)"
        echo "# Build ID: $(git rev-parse HEAD 2>/dev/null || echo "Unknown")"
        echo "# Build branch: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "Unknown")"
        echo "# Build tag: $(git describe --tags 2>/dev/null || echo "Unknown")"
        echo "# Build commit: $(git rev-parse --short HEAD 2>/dev/null || echo "Unknown")"
        echo "# Build author: $(git log -1 --pretty=format:'%an <%ae>' 2>/dev/null || echo "Unknown")"
        echo "# Build message: $(git log -1 --pretty=format:'%s' 2>/dev/null || echo "Unknown")"
    }
    __nnf "$@" || usage "$?" "ywt:info" "$@" && return 1
}
(
    export -f ywt:info
)
