name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Install Alpine Depencencies
        shell: sh
        run: |
          apk add --update bash gpg
      - uses: actions/checkout@v4
      - name: Install YDK Shell SDK
        run: |
          packages/ydk/ydk.cli.sh install
      - name: Packing YDK Shell SDK
        run: |
          packages/ydk/ydk.cli.sh packer pack "$(realpath ./packages/ydk/ydk.cli.sh)"
      - name: Docker Setup Buildx      
        uses: docker/setup-buildx-action@v3.3.0
        with:
          # Buildx version. (eg. v0.3.0)
          # version: # optional
          # # Sets the builder driver to be used
          # driver: # optional, default is docker-container
          # # List of additional driver-specific options. (eg. image=moby/buildkit:master)
          # driver-opts: # optional
          # # BuildKit daemon flags
          # buildkitd-flags: # optional, default is --allow-insecure-entitlement security.  insecure --allow-insecure-entitlement network.host
          # # BuildKit daemon config file
          # buildkitd-config: # optional
          # # Inline BuildKit daemon config
          # buildkitd-config-inline: # optional
          # Sets up docker build command as an alias to docker buildx build
          install: true # optional, default is false
          # Switch to this builder instance
          use: true # optional, default is true
          # # Optional address for docker socket or context from `docker context ls`
          # endpoint: # optional
          # # Fixed platforms for current node. If not empty, values take priority over   the detected ones
          # platforms: # optional
          # # Append additional nodes to the builder
          # append: # optional
          # # Cache buildx binary to GitHub Actions cache backend
          # cache-binary: # optional, default is true
          # # Cleanup temp files and remove builder at the end of a job
          # cleanup: # optional, default is true
          # # BuildKit daemon config file
          # config: # optional
          # # Inline BuildKit daemon config
          # config-inline: # optional              
      - name: Build the Docker image
        run: |
          docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # "centos:latest", "opensuse/leap:latest" "archlinux:latest" "fedora:latest"
        container: ["ubuntu:latest", "alpine:latest", "kalilinux/kali-rolling", "debian:latest"]
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Alpine Depencencies
      shell: sh
      run: |
        apk add --update bash
      if: matrix.container == 'alpine:latest'    
    - name: Install YDK Shell SDK
      run: |
        packages/ydk/ydk.cli.sh install
    - name: Packing YDK Shell SDK
      run: |
        packages/ydk/ydk.cli.sh packer pack ./packages/ydk/ydk.cli.sh

# - name: Install Depencencies
#   shell: bash
#   run: |
#     apt-get update
#     apt-get install -y curl gnupg docker.io
#   if: matrix.container != 'alpine:latest'    
# - name: Build the Docker image
#   run: |
#    docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     # container:
#     #   image: alpine:latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: |
#        docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
#     - name: Install YDK Shell SDK
#       run: |
#         apk add --update > /dev/null 
#         apk add --no-cache bash > /dev/null 
#         packages/ydk/ydk.cli.sh install
    
