name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      # - name: Install Alpine Depencencies
      #   shell: sh
      #   run: |
      #     apk add --update bash
      - uses: actions/checkout@v4
      - name: Show Variables
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
          echo "GITHUB_API_URL: $GITHUB_API_URL"
          echo "GITHUB_GRAPHQL_URL: $GITHUB_GRAPHQL_URL"
          echo "RUNNER_OS: $RUNNER_OS"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
          echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
          echo "ACTIONS_RUNTIME_URL: $ACTIONS_RUNTIME_URL"
          echo "ACTIONS_RUNTIME_TOKEN: $ACTIONS_RUNTIME_TOKEN"
          echo "ACTIONS_CACHE_URL: $ACTIONS_CACHE_URL"
          echo "ACTIONS_RUNTIME_API_URL: $ACTIONS_RUNTIME_API_URL"
          echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_SERVER_URL: $GITHUB_SERVER_URL"
          echo "GITHUB_API_URL: $GITHUB_API_URL"
          echo "GITHUB_GRAPHQL_URL: $GITHUB_GRAPHQL_URL"
          echo "RUNNER_OS: $RUNNER_OS"
          echo "RUNNER_TEMP: $RUNNER_TEMP"
          echo "RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
          echo "RUNNER_WORKSPACE: $RUNNER_WORKSPACE"
          echo "ACTIONS_RUNTIME_URL: $ACTIONS_RUNTIME_URL"          
      - name: Install YDK Shell SDK
        run: |
          packages/ydk/ydk.cli.sh install
      - name: Build YDK Shell SDK
        run: |
          packages/ydk/ydk.cli.sh packer build "$(realpath ./packages/ydk/ydk.cli.sh)" "31/12/2999"
      - name: Commit SDK and Tag
        working-directory: ${{ github.workspace }}
        if: false
        run: |
            git add /packages/ydk/ydk.sh
            git commit -m "YDK Shell SDK. Build ${{ github.run_number }}"
            git tag -a "0.0.0-dev-0" -m "YDK Shell SDK. Build ${{ github.run_number }}"
      - name: Attest artifact
        uses: github-early-access/generate-build-provenance@main
        with:
          subject-path: '${{ github.workspace }}/packages/ydk'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ydk.sh
          path: |
            ${{ github.workspace }}/packages/ydk/ydk.sh
            ${{ github.workspace }}/packages/ydk/ydk.bin
            ${{ github.workspace }}/packages/ydk/ydk.sh.x.c
            ${{ github.workspace }}/packages/ydk/ydk.sh.checksum

  Docker:
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # "centos:latest", "opensuse/leap:latest" "archlinux:latest" "fedora:latest"
        container: ["ubuntu:latest", "alpine:latest", "kalilinux/kali-rolling", "debian:latest"]
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Alpine Depencencies
      shell: sh
      run: |
        apk add --update bash
      if: matrix.container == 'alpine:latest'    
    - name: Install YDK Shell SDK
      run: |
        packages/ydk/ydk.cli.sh install
    - name: Packing YDK Shell SDK
      run: |
        packages/ydk/ydk.cli.sh packer pack ./packages/ydk/ydk.cli.sh

# - name: Install Depencencies
#   shell: bash
#   run: |
#     apt-get update
#     apt-get install -y curl gnupg docker.io
#   if: matrix.container != 'alpine:latest'    
# - name: Build the Docker image
#   run: |
#    docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     # container:
#     #   image: alpine:latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: |
#        docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
#     - name: Install YDK Shell SDK
#       run: |
#         apk add --update > /dev/null 
#         apk add --no-cache bash > /dev/null 
#         packages/ydk/ydk.cli.sh install
    
