name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    - name: Build the Docker image
     run: |
       docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)

    container:
      image: alpine:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install YDK Shell SDK
      run: |
        apk add --update > /dev/null 
        apk add --no-cache bash > /dev/null 
        packages/ydk/ydk.cli.sh install
    
