name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["ubuntu:latest", "alpine:latest", "kalilinux/kali-rolling"]
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Alpine Depencencies
      shell: sh
      run: |
        apk add --update bash curl gnupg docker
      if: matrix.container == 'alpine:latest'
    - name: Install Depencencies
      shell: bash
      run: |
        apt-get update
        apt-get install -y curl gnupg docker.io
      if: matrix.container != 'alpine:latest'
    - name: Start Docker service
      run: |
        service docker start
    - name: Build the Docker image
      run: |
       docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
    - name: Install YDK Shell SDK
      run: |
        packages/ydk/ydk.cli.sh install

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     # container:
#     #   image: alpine:latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: |
#        docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
#     - name: Install YDK Shell SDK
#       run: |
#         apk add --update > /dev/null 
#         apk add --no-cache bash > /dev/null 
#         packages/ydk/ydk.cli.sh install
    
