name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["ubuntu:latest", "alpine:latest", "kali/kali-rolling"]
    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Depencencies
      shell: bash
      run: |
        if [ "${{ matrix.container }}" == "alpine:latest" ]; then
          apk add --update
          apk add --no-cache bash
        fi        
    - name: Build the Docker image
      run: |
       docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
    - name: Install YDK Shell SDK
      run: |
        packages/ydk/ydk.cli.sh install

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     # container:
#     #   image: alpine:latest
#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: |
#        docker build . --no-cache --file docker/ywt-shell/Dockerfile.alpine --tag ydk-shell:$(date +%s)
#     - name: Install YDK Shell SDK
#       run: |
#         apk add --update > /dev/null 
#         apk add --no-cache bash > /dev/null 
#         packages/ydk/ydk.cli.sh install
    
